name: run-deploy-front-end

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://andre831/ci-cd-training:express-training
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
