name: template-action

on:
  push:
    branches: [main]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi line script
        run: |
          echo Testandooo
          echo Testando 2

  name: Greeting 2
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run a multi line script
          run: |
            echo 2
            echo 22
